env: "local"

log:
  level: debug
  output: stdout
  file: logs/app.log

storage:
  type: "mongodb"

  postgres:
    host: postgres-notifications
    port: 5432
    name: notification_service
    ssl_mode: disable
    connect_timeout: 5s
    max_retries_time: 2s

  mongodb:
    uri: mongodb://mongo-notifications:27017/?directConnection=true
    name: notifications_service
    connect_timeout: 5s

auth_grpc:
  addr: auth_service:50051

kafka:
  brokers: kafka:29092
  topic: notifications
