// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package services

import (
	"context"
	"notifications/internal/domain/entities"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockNotificationRepository creates a new instance of MockNotificationRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockNotificationRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockNotificationRepository {
	mock := &MockNotificationRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockNotificationRepository is an autogenerated mock type for the NotificationRepository type
type MockNotificationRepository struct {
	mock.Mock
}

type MockNotificationRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockNotificationRepository) EXPECT() *MockNotificationRepository_Expecter {
	return &MockNotificationRepository_Expecter{mock: &_m.Mock}
}

// GetById provides a mock function for the type MockNotificationRepository
func (_mock *MockNotificationRepository) GetById(ctx context.Context, id uuid.UUID) (*entities.Notification, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetById")
	}

	var r0 *entities.Notification
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*entities.Notification, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *entities.Notification); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Notification)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockNotificationRepository_GetById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetById'
type MockNotificationRepository_GetById_Call struct {
	*mock.Call
}

// GetById is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockNotificationRepository_Expecter) GetById(ctx interface{}, id interface{}) *MockNotificationRepository_GetById_Call {
	return &MockNotificationRepository_GetById_Call{Call: _e.mock.On("GetById", ctx, id)}
}

func (_c *MockNotificationRepository_GetById_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockNotificationRepository_GetById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockNotificationRepository_GetById_Call) Return(notification *entities.Notification, err error) *MockNotificationRepository_GetById_Call {
	_c.Call.Return(notification, err)
	return _c
}

func (_c *MockNotificationRepository_GetById_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (*entities.Notification, error)) *MockNotificationRepository_GetById_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type MockNotificationRepository
func (_mock *MockNotificationRepository) Save(ctx context.Context, notification *entities.Notification) error {
	ret := _mock.Called(ctx, notification)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entities.Notification) error); ok {
		r0 = returnFunc(ctx, notification)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockNotificationRepository_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockNotificationRepository_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - notification *entities.Notification
func (_e *MockNotificationRepository_Expecter) Save(ctx interface{}, notification interface{}) *MockNotificationRepository_Save_Call {
	return &MockNotificationRepository_Save_Call{Call: _e.mock.On("Save", ctx, notification)}
}

func (_c *MockNotificationRepository_Save_Call) Run(run func(ctx context.Context, notification *entities.Notification)) *MockNotificationRepository_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entities.Notification
		if args[1] != nil {
			arg1 = args[1].(*entities.Notification)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockNotificationRepository_Save_Call) Return(err error) *MockNotificationRepository_Save_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockNotificationRepository_Save_Call) RunAndReturn(run func(ctx context.Context, notification *entities.Notification) error) *MockNotificationRepository_Save_Call {
	_c.Call.Return(run)
	return _c
}
