apiVersion: apps/v1
kind: Deployment
metadata:
  name: mailpit
  labels:
    app: mailpit
    {{- include "goflow.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mailpit
  template:
    metadata:
      labels:
        app: mailpit
    spec:
      containers:
        - name: mailpit
          image: {{ .Values.infra.mailpit.image }}
          ports:
            - containerPort: 1025
              name: smtp
            - containerPort: 8025
              name: http
          env:
            - name: MP_MAX_MESSAGES
              value: "500"
          resources:
            {{- toYaml .Values.infra.mailpit.resources | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: mailpit
  labels:
    {{- include "goflow.labels" . | nindent 4 }}
spec:
  selector:
    app: mailpit
  ports:
    - name: smtp
      port: 1025
      targetPort: 1025
    - name: http
      port: 8025
      targetPort: 8025
