apiVersion: v1
kind: Secret
metadata:
  name: goflow-secrets
  labels:
    {{- include "goflow.labels" . | nindent 4 }}
type: Opaque
stringData:
  DB_USER: {{ .Values.secrets.dbUser | quote }}
  DB_PASSWORD: {{ .Values.secrets.dbPassword | quote }}
  BOOTSTRAP_TOKEN: {{ .Values.secrets.bootstrapToken | quote }}
  jwt-private.pem: |
    -----BEGIN PRIVATE KEY-----
    MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQDrgUASTiSFkJrD
    M860EeL4NstCQ6wfqSiGDL9sOzYBAsadqnknQo0rI8XSXV/lLTQ7MrYlQeNPlFBE
    0Ex+RhKV+TzLuCQ4ovkxfVsa4Yq5N58vC9ZeOdVwfLY7+uDJHOtVmrg7Aef8Qogg
    Xwi0kTs3Y7rKSxIqhnG8RqrRt5nwixZEFcgPXHdrW96uTfmESZE75AFzVPoRApMM
    6ipPgLS/bB60jF6xbkYMfkgglajeqbUxQXwNCG9MP5LOUdmyqa/szmETUFFiczel
    5ok0SBTqhSa3htZC2bUjVPTLypM6YACeiaWPOdp7t4j0v2TuAs58VYxcGAc/JamW
    0bm/Gk5vAgMBAAECggEAOiVWYW6ju8qBO5LuBS2pYWl98+VreQG1/KrnFFzmL4e0
    7Dar5RKccjtJ22+sfpQTok4aBMbozbwruWHIkSDR8+9uoEndv5IVfq+Zr+Bh9OsT
    xXThv6/9z+EqyVJe76jRPfiOZhtJYNI4c+2i45o8Caf49Xtlh9Rb/oVgJZl0S5xC
    aUzkXpTtSeNts/TeqyaeYsXaWQJaWgMEyXy0zogJvEG7+HcHgqpdSCe7FoiRhroY
    wZ+DDgFQvlw+sgci/H++37FqHng065W58CDfvz0EYnxlnkClbNQYHPK+FqLHmNGm
    +9YZrUK4P8AQw+yqYj4DjOvKpLNIq5OLBpYG5mgIKQKBgQD3wyspJUqxm00zkyTQ
    WeUXzSvC/5b9GbY/FkqjM/asbYThyBUC6uDEOIzwR8EN/CLjEC5555C+ydMHlk16
    gn7BHbfKMrmRClYQsIgYH578XGMwT2wKOnsgFr7IL1K5z0cGIniEs4c3r8/Hw/U7
    jmLdUGiJSSPQAOdDhEuP35YgYwKBgQDzVcB+nbpxVNTxpV071YYiC/oW0pgLKuJ5
    Ahn2RzUqD7+GC5oeIDpylYNFvln9ut6Kbshq13rXg2/NVJ/IEk1GPqtbgLlgnU4H
    53MK7C2idYjQOGJgXPTNxFGGuMYo4L0f7N6Wf2RELelcOJEbKu85eYXFWTNR62rU
    mJMlGqgJhQKBgCyD7XpMD/qPO7S7iE7DCA1ZuLYlc/xvpTX6jFh8WqKqXsiuSVAn
    4VCAFJqLWd1oYuBHJQKUH4aX/omLcMpFLf8GluIGcR7lK4d+IEWtUMRo2Q1yB6hi
    z4J5c7fGAOgPnOQ2R08YboAL35o11BbqQ0seSln4QS37K5IO8ACenHufAoGAaBtt
    Ev7akLhRrt0oCXxuOczT/8W0BTsgz9LlVqfaiBdawrfeBTuWpgVvt3wcNmEn6yRA
    nO16AhCa2cd14PxrkT0oxSpKpZpHkzwjzS2EzLfqg+NLu5yppAt1MeWF6mFUqP8H
    sG3qcP0PlUQiWPRCi12BrRBf05GcED8C3WINOJ0CgYAygvWHp04NS+7nobHcF4Ir
    QURAH61QlZE5+7R4U+9jsvXZ9C9DcQKzbUAtIikk6uUUbkvQpD9XzpFch1CH+kp8
    AbEE+Ar9SZ4k9CnjCJIgFYKWhomIWcK4WnQcLcdj1bMqgFd9dA6zmMXdEOMiygKY
    yneZSg7opjbLCXQPukbBQA==
    -----END PRIVATE KEY-----
  jwt-public.pem: |
    -----BEGIN PUBLIC KEY-----
    MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA64FAEk4khZCawzPOtBHi
    +DbLQkOsH6kohgy/bDs2AQLGnap5J0KNKyPF0l1f5S00OzK2JUHjT5RQRNBMfkYS
    lfk8y7gkOKL5MX1bGuGKuTefLwvWXjnVcHy2O/rgyRzrVZq4OwHn/EKIIF8ItJE7
    N2O6yksSKoZxvEaq0beZ8IsWRBXID1x3a1verk35hEmRO+QBc1T6EQKTDOoqT4C0
    v2wetIxesW5GDH5IIJWo3qm1MUF8DQhvTD+SzlHZsqmv7M5hE1BRYnM3peaJNEgU
    6oUmt4bWQtm1I1T0y8qTOmAAnomljznae7eI9L9k7gLOfFWMXBgHPyWpltG5vxpO
    bwIDAQAB
    -----END PUBLIC KEY-----
