apiVersion: v1
kind: Secret
metadata:
  name: goflow-secrets
  labels:
    {{- include "goflow.labels" . | nindent 4 }}
type: Opaque
stringData:
  DB_USER: {{ .Values.secrets.dbUser | quote }}
  DB_PASSWORD: {{ .Values.secrets.dbPassword | quote }}
  BOOTSTRAP_TOKEN: {{ .Values.secrets.bootstrapToken | quote }}
  jwt-private.pem: {{ .Values.secrets.jwtPrivateKey | quote }}
  jwt-public.pem: {{ .Values.secrets.jwtPublicKey | quote }}
