// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package services

import (
	"context"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockCacheRepository creates a new instance of MockCacheRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCacheRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCacheRepository {
	mock := &MockCacheRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCacheRepository is an autogenerated mock type for the CacheRepository type
type MockCacheRepository struct {
	mock.Mock
}

type MockCacheRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCacheRepository) EXPECT() *MockCacheRepository_Expecter {
	return &MockCacheRepository_Expecter{mock: &_m.Mock}
}

// GetCompanyId provides a mock function for the type MockCacheRepository
func (_mock *MockCacheRepository) GetCompanyId(ctx context.Context, accountId uuid.UUID) (uuid.UUID, error) {
	ret := _mock.Called(ctx, accountId)

	if len(ret) == 0 {
		panic("no return value specified for GetCompanyId")
	}

	var r0 uuid.UUID
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (uuid.UUID, error)); ok {
		return returnFunc(ctx, accountId)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) uuid.UUID); ok {
		r0 = returnFunc(ctx, accountId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, accountId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCacheRepository_GetCompanyId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCompanyId'
type MockCacheRepository_GetCompanyId_Call struct {
	*mock.Call
}

// GetCompanyId is a helper method to define mock.On call
//   - ctx context.Context
//   - accountId uuid.UUID
func (_e *MockCacheRepository_Expecter) GetCompanyId(ctx interface{}, accountId interface{}) *MockCacheRepository_GetCompanyId_Call {
	return &MockCacheRepository_GetCompanyId_Call{Call: _e.mock.On("GetCompanyId", ctx, accountId)}
}

func (_c *MockCacheRepository_GetCompanyId_Call) Run(run func(ctx context.Context, accountId uuid.UUID)) *MockCacheRepository_GetCompanyId_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCacheRepository_GetCompanyId_Call) Return(uUID uuid.UUID, err error) *MockCacheRepository_GetCompanyId_Call {
	_c.Call.Return(uUID, err)
	return _c
}

func (_c *MockCacheRepository_GetCompanyId_Call) RunAndReturn(run func(ctx context.Context, accountId uuid.UUID) (uuid.UUID, error)) *MockCacheRepository_GetCompanyId_Call {
	_c.Call.Return(run)
	return _c
}

// SetCompanyId provides a mock function for the type MockCacheRepository
func (_mock *MockCacheRepository) SetCompanyId(ctx context.Context, accountId uuid.UUID, companyId uuid.UUID) error {
	ret := _mock.Called(ctx, accountId, companyId)

	if len(ret) == 0 {
		panic("no return value specified for SetCompanyId")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, accountId, companyId)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCacheRepository_SetCompanyId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetCompanyId'
type MockCacheRepository_SetCompanyId_Call struct {
	*mock.Call
}

// SetCompanyId is a helper method to define mock.On call
//   - ctx context.Context
//   - accountId uuid.UUID
//   - companyId uuid.UUID
func (_e *MockCacheRepository_Expecter) SetCompanyId(ctx interface{}, accountId interface{}, companyId interface{}) *MockCacheRepository_SetCompanyId_Call {
	return &MockCacheRepository_SetCompanyId_Call{Call: _e.mock.On("SetCompanyId", ctx, accountId, companyId)}
}

func (_c *MockCacheRepository_SetCompanyId_Call) Run(run func(ctx context.Context, accountId uuid.UUID, companyId uuid.UUID)) *MockCacheRepository_SetCompanyId_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockCacheRepository_SetCompanyId_Call) Return(err error) *MockCacheRepository_SetCompanyId_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCacheRepository_SetCompanyId_Call) RunAndReturn(run func(ctx context.Context, accountId uuid.UUID, companyId uuid.UUID) error) *MockCacheRepository_SetCompanyId_Call {
	_c.Call.Return(run)
	return _c
}
