// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package services

import (
	"context"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAccountClient creates a new instance of MockAccountClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAccountClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAccountClient {
	mock := &MockAccountClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAccountClient is an autogenerated mock type for the AccountClient type
type MockAccountClient struct {
	mock.Mock
}

type MockAccountClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAccountClient) EXPECT() *MockAccountClient_Expecter {
	return &MockAccountClient_Expecter{mock: &_m.Mock}
}

// GetCompanyIdByAccountId provides a mock function for the type MockAccountClient
func (_mock *MockAccountClient) GetCompanyIdByAccountId(ctx context.Context, accountId uuid.UUID) (uuid.UUID, error) {
	ret := _mock.Called(ctx, accountId)

	if len(ret) == 0 {
		panic("no return value specified for GetCompanyIdByAccountId")
	}

	var r0 uuid.UUID
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (uuid.UUID, error)); ok {
		return returnFunc(ctx, accountId)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) uuid.UUID); ok {
		r0 = returnFunc(ctx, accountId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, accountId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAccountClient_GetCompanyIdByAccountId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCompanyIdByAccountId'
type MockAccountClient_GetCompanyIdByAccountId_Call struct {
	*mock.Call
}

// GetCompanyIdByAccountId is a helper method to define mock.On call
//   - ctx context.Context
//   - accountId uuid.UUID
func (_e *MockAccountClient_Expecter) GetCompanyIdByAccountId(ctx interface{}, accountId interface{}) *MockAccountClient_GetCompanyIdByAccountId_Call {
	return &MockAccountClient_GetCompanyIdByAccountId_Call{Call: _e.mock.On("GetCompanyIdByAccountId", ctx, accountId)}
}

func (_c *MockAccountClient_GetCompanyIdByAccountId_Call) Run(run func(ctx context.Context, accountId uuid.UUID)) *MockAccountClient_GetCompanyIdByAccountId_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAccountClient_GetCompanyIdByAccountId_Call) Return(uUID uuid.UUID, err error) *MockAccountClient_GetCompanyIdByAccountId_Call {
	_c.Call.Return(uUID, err)
	return _c
}

func (_c *MockAccountClient_GetCompanyIdByAccountId_Call) RunAndReturn(run func(ctx context.Context, accountId uuid.UUID) (uuid.UUID, error)) *MockAccountClient_GetCompanyIdByAccountId_Call {
	_c.Call.Return(run)
	return _c
}
