// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package services

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockEmailSender creates a new instance of MockEmailSender. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEmailSender(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEmailSender {
	mock := &MockEmailSender{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockEmailSender is an autogenerated mock type for the EmailSender type
type MockEmailSender struct {
	mock.Mock
}

type MockEmailSender_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEmailSender) EXPECT() *MockEmailSender_Expecter {
	return &MockEmailSender_Expecter{mock: &_m.Mock}
}

// Send provides a mock function for the type MockEmailSender
func (_mock *MockEmailSender) Send(ctx context.Context, email string, title string, message string) error {
	ret := _mock.Called(ctx, email, title, message)

	if len(ret) == 0 {
		panic("no return value specified for Send")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = returnFunc(ctx, email, title, message)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockEmailSender_Send_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Send'
type MockEmailSender_Send_Call struct {
	*mock.Call
}

// Send is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
//   - title string
//   - message string
func (_e *MockEmailSender_Expecter) Send(ctx interface{}, email interface{}, title interface{}, message interface{}) *MockEmailSender_Send_Call {
	return &MockEmailSender_Send_Call{Call: _e.mock.On("Send", ctx, email, title, message)}
}

func (_c *MockEmailSender_Send_Call) Run(run func(ctx context.Context, email string, title string, message string)) *MockEmailSender_Send_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockEmailSender_Send_Call) Return(err error) *MockEmailSender_Send_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockEmailSender_Send_Call) RunAndReturn(run func(ctx context.Context, email string, title string, message string) error) *MockEmailSender_Send_Call {
	_c.Call.Return(run)
	return _c
}
