// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package services

import (
	"context"
	"notifications/internal/dto/response"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockUserClient creates a new instance of MockUserClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserClient {
	mock := &MockUserClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUserClient is an autogenerated mock type for the UserClient type
type MockUserClient struct {
	mock.Mock
}

type MockUserClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserClient) EXPECT() *MockUserClient_Expecter {
	return &MockUserClient_Expecter{mock: &_m.Mock}
}

// GetUsersByCompanyId provides a mock function for the type MockUserClient
func (_mock *MockUserClient) GetUsersByCompanyId(ctx context.Context, companyId uuid.UUID) ([]*response.UserResponse, error) {
	ret := _mock.Called(ctx, companyId)

	if len(ret) == 0 {
		panic("no return value specified for GetUsersByCompanyId")
	}

	var r0 []*response.UserResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]*response.UserResponse, error)); ok {
		return returnFunc(ctx, companyId)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) []*response.UserResponse); ok {
		r0 = returnFunc(ctx, companyId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*response.UserResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, companyId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserClient_GetUsersByCompanyId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUsersByCompanyId'
type MockUserClient_GetUsersByCompanyId_Call struct {
	*mock.Call
}

// GetUsersByCompanyId is a helper method to define mock.On call
//   - ctx context.Context
//   - companyId uuid.UUID
func (_e *MockUserClient_Expecter) GetUsersByCompanyId(ctx interface{}, companyId interface{}) *MockUserClient_GetUsersByCompanyId_Call {
	return &MockUserClient_GetUsersByCompanyId_Call{Call: _e.mock.On("GetUsersByCompanyId", ctx, companyId)}
}

func (_c *MockUserClient_GetUsersByCompanyId_Call) Run(run func(ctx context.Context, companyId uuid.UUID)) *MockUserClient_GetUsersByCompanyId_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserClient_GetUsersByCompanyId_Call) Return(userResponses []*response.UserResponse, err error) *MockUserClient_GetUsersByCompanyId_Call {
	_c.Call.Return(userResponses, err)
	return _c
}

func (_c *MockUserClient_GetUsersByCompanyId_Call) RunAndReturn(run func(ctx context.Context, companyId uuid.UUID) ([]*response.UserResponse, error)) *MockUserClient_GetUsersByCompanyId_Call {
	_c.Call.Return(run)
	return _c
}
