apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: goflow
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://git.iu7.bmstu.ru/pdv23u605/ppo.git'
    targetRevision: main
    path: deploy/helm/goflow
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: goflow
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
  ignoreDifferences:
    - group: ""
      kind: Secret
      name: goflow-secrets
      jsonPointers:
        - /data/jwt-private.pem
        - /data/jwt-public.pem
