// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package services

import (
	"accounts/internal/domain/entities"
	"context"
	"time"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockStatementRepository creates a new instance of MockStatementRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStatementRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStatementRepository {
	mock := &MockStatementRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockStatementRepository is an autogenerated mock type for the StatementRepository type
type MockStatementRepository struct {
	mock.Mock
}

type MockStatementRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStatementRepository) EXPECT() *MockStatementRepository_Expecter {
	return &MockStatementRepository_Expecter{mock: &_m.Mock}
}

// GetByAccountIdAndPeriod provides a mock function for the type MockStatementRepository
func (_mock *MockStatementRepository) GetByAccountIdAndPeriod(ctx context.Context, accountId uuid.UUID, from time.Time, to time.Time) (*entities.Statement, error) {
	ret := _mock.Called(ctx, accountId, from, to)

	if len(ret) == 0 {
		panic("no return value specified for GetByAccountIdAndPeriod")
	}

	var r0 *entities.Statement
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, time.Time, time.Time) (*entities.Statement, error)); ok {
		return returnFunc(ctx, accountId, from, to)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, time.Time, time.Time) *entities.Statement); ok {
		r0 = returnFunc(ctx, accountId, from, to)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Statement)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, time.Time, time.Time) error); ok {
		r1 = returnFunc(ctx, accountId, from, to)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStatementRepository_GetByAccountIdAndPeriod_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByAccountIdAndPeriod'
type MockStatementRepository_GetByAccountIdAndPeriod_Call struct {
	*mock.Call
}

// GetByAccountIdAndPeriod is a helper method to define mock.On call
//   - ctx context.Context
//   - accountId uuid.UUID
//   - from time.Time
//   - to time.Time
func (_e *MockStatementRepository_Expecter) GetByAccountIdAndPeriod(ctx interface{}, accountId interface{}, from interface{}, to interface{}) *MockStatementRepository_GetByAccountIdAndPeriod_Call {
	return &MockStatementRepository_GetByAccountIdAndPeriod_Call{Call: _e.mock.On("GetByAccountIdAndPeriod", ctx, accountId, from, to)}
}

func (_c *MockStatementRepository_GetByAccountIdAndPeriod_Call) Run(run func(ctx context.Context, accountId uuid.UUID, from time.Time, to time.Time)) *MockStatementRepository_GetByAccountIdAndPeriod_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		var arg3 time.Time
		if args[3] != nil {
			arg3 = args[3].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockStatementRepository_GetByAccountIdAndPeriod_Call) Return(statement *entities.Statement, err error) *MockStatementRepository_GetByAccountIdAndPeriod_Call {
	_c.Call.Return(statement, err)
	return _c
}

func (_c *MockStatementRepository_GetByAccountIdAndPeriod_Call) RunAndReturn(run func(ctx context.Context, accountId uuid.UUID, from time.Time, to time.Time) (*entities.Statement, error)) *MockStatementRepository_GetByAccountIdAndPeriod_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type MockStatementRepository
func (_mock *MockStatementRepository) Save(ctx context.Context, statement *entities.Statement) error {
	ret := _mock.Called(ctx, statement)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entities.Statement) error); ok {
		r0 = returnFunc(ctx, statement)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStatementRepository_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockStatementRepository_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - statement *entities.Statement
func (_e *MockStatementRepository_Expecter) Save(ctx interface{}, statement interface{}) *MockStatementRepository_Save_Call {
	return &MockStatementRepository_Save_Call{Call: _e.mock.On("Save", ctx, statement)}
}

func (_c *MockStatementRepository_Save_Call) Run(run func(ctx context.Context, statement *entities.Statement)) *MockStatementRepository_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entities.Statement
		if args[1] != nil {
			arg1 = args[1].(*entities.Statement)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStatementRepository_Save_Call) Return(err error) *MockStatementRepository_Save_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStatementRepository_Save_Call) RunAndReturn(run func(ctx context.Context, statement *entities.Statement) error) *MockStatementRepository_Save_Call {
	_c.Call.Return(run)
	return _c
}
