// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package services

import (
	"accounts/internal/domain/entities"
	"context"
	"time"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockBankOperationRepository creates a new instance of MockBankOperationRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBankOperationRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBankOperationRepository {
	mock := &MockBankOperationRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockBankOperationRepository is an autogenerated mock type for the BankOperationRepository type
type MockBankOperationRepository struct {
	mock.Mock
}

type MockBankOperationRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBankOperationRepository) EXPECT() *MockBankOperationRepository_Expecter {
	return &MockBankOperationRepository_Expecter{mock: &_m.Mock}
}

// GetByAccountIdAndPeriod provides a mock function for the type MockBankOperationRepository
func (_mock *MockBankOperationRepository) GetByAccountIdAndPeriod(ctx context.Context, accountId uuid.UUID, from time.Time, to time.Time) ([]*entities.BankOperation, error) {
	ret := _mock.Called(ctx, accountId, from, to)

	if len(ret) == 0 {
		panic("no return value specified for GetByAccountIdAndPeriod")
	}

	var r0 []*entities.BankOperation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, time.Time, time.Time) ([]*entities.BankOperation, error)); ok {
		return returnFunc(ctx, accountId, from, to)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, time.Time, time.Time) []*entities.BankOperation); ok {
		r0 = returnFunc(ctx, accountId, from, to)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entities.BankOperation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, time.Time, time.Time) error); ok {
		r1 = returnFunc(ctx, accountId, from, to)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBankOperationRepository_GetByAccountIdAndPeriod_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByAccountIdAndPeriod'
type MockBankOperationRepository_GetByAccountIdAndPeriod_Call struct {
	*mock.Call
}

// GetByAccountIdAndPeriod is a helper method to define mock.On call
//   - ctx context.Context
//   - accountId uuid.UUID
//   - from time.Time
//   - to time.Time
func (_e *MockBankOperationRepository_Expecter) GetByAccountIdAndPeriod(ctx interface{}, accountId interface{}, from interface{}, to interface{}) *MockBankOperationRepository_GetByAccountIdAndPeriod_Call {
	return &MockBankOperationRepository_GetByAccountIdAndPeriod_Call{Call: _e.mock.On("GetByAccountIdAndPeriod", ctx, accountId, from, to)}
}

func (_c *MockBankOperationRepository_GetByAccountIdAndPeriod_Call) Run(run func(ctx context.Context, accountId uuid.UUID, from time.Time, to time.Time)) *MockBankOperationRepository_GetByAccountIdAndPeriod_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		var arg3 time.Time
		if args[3] != nil {
			arg3 = args[3].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockBankOperationRepository_GetByAccountIdAndPeriod_Call) Return(bankOperations []*entities.BankOperation, err error) *MockBankOperationRepository_GetByAccountIdAndPeriod_Call {
	_c.Call.Return(bankOperations, err)
	return _c
}

func (_c *MockBankOperationRepository_GetByAccountIdAndPeriod_Call) RunAndReturn(run func(ctx context.Context, accountId uuid.UUID, from time.Time, to time.Time) ([]*entities.BankOperation, error)) *MockBankOperationRepository_GetByAccountIdAndPeriod_Call {
	_c.Call.Return(run)
	return _c
}

// GetByIdempotencyKey provides a mock function for the type MockBankOperationRepository
func (_mock *MockBankOperationRepository) GetByIdempotencyKey(ctx context.Context, idempotencyKey string) (*entities.BankOperation, error) {
	ret := _mock.Called(ctx, idempotencyKey)

	if len(ret) == 0 {
		panic("no return value specified for GetByIdempotencyKey")
	}

	var r0 *entities.BankOperation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*entities.BankOperation, error)); ok {
		return returnFunc(ctx, idempotencyKey)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *entities.BankOperation); ok {
		r0 = returnFunc(ctx, idempotencyKey)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.BankOperation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, idempotencyKey)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBankOperationRepository_GetByIdempotencyKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByIdempotencyKey'
type MockBankOperationRepository_GetByIdempotencyKey_Call struct {
	*mock.Call
}

// GetByIdempotencyKey is a helper method to define mock.On call
//   - ctx context.Context
//   - idempotencyKey string
func (_e *MockBankOperationRepository_Expecter) GetByIdempotencyKey(ctx interface{}, idempotencyKey interface{}) *MockBankOperationRepository_GetByIdempotencyKey_Call {
	return &MockBankOperationRepository_GetByIdempotencyKey_Call{Call: _e.mock.On("GetByIdempotencyKey", ctx, idempotencyKey)}
}

func (_c *MockBankOperationRepository_GetByIdempotencyKey_Call) Run(run func(ctx context.Context, idempotencyKey string)) *MockBankOperationRepository_GetByIdempotencyKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBankOperationRepository_GetByIdempotencyKey_Call) Return(bankOperation *entities.BankOperation, err error) *MockBankOperationRepository_GetByIdempotencyKey_Call {
	_c.Call.Return(bankOperation, err)
	return _c
}

func (_c *MockBankOperationRepository_GetByIdempotencyKey_Call) RunAndReturn(run func(ctx context.Context, idempotencyKey string) (*entities.BankOperation, error)) *MockBankOperationRepository_GetByIdempotencyKey_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type MockBankOperationRepository
func (_mock *MockBankOperationRepository) Save(ctx context.Context, operation *entities.BankOperation) error {
	ret := _mock.Called(ctx, operation)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entities.BankOperation) error); ok {
		r0 = returnFunc(ctx, operation)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBankOperationRepository_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockBankOperationRepository_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - operation *entities.BankOperation
func (_e *MockBankOperationRepository_Expecter) Save(ctx interface{}, operation interface{}) *MockBankOperationRepository_Save_Call {
	return &MockBankOperationRepository_Save_Call{Call: _e.mock.On("Save", ctx, operation)}
}

func (_c *MockBankOperationRepository_Save_Call) Run(run func(ctx context.Context, operation *entities.BankOperation)) *MockBankOperationRepository_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entities.BankOperation
		if args[1] != nil {
			arg1 = args[1].(*entities.BankOperation)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBankOperationRepository_Save_Call) Return(err error) *MockBankOperationRepository_Save_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBankOperationRepository_Save_Call) RunAndReturn(run func(ctx context.Context, operation *entities.BankOperation) error) *MockBankOperationRepository_Save_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateStatusAndExternalID provides a mock function for the type MockBankOperationRepository
func (_mock *MockBankOperationRepository) UpdateStatusAndExternalID(ctx context.Context, operationId uuid.UUID, status string, externalID string) error {
	ret := _mock.Called(ctx, operationId, status, externalID)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatusAndExternalID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, string) error); ok {
		r0 = returnFunc(ctx, operationId, status, externalID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBankOperationRepository_UpdateStatusAndExternalID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateStatusAndExternalID'
type MockBankOperationRepository_UpdateStatusAndExternalID_Call struct {
	*mock.Call
}

// UpdateStatusAndExternalID is a helper method to define mock.On call
//   - ctx context.Context
//   - operationId uuid.UUID
//   - status string
//   - externalID string
func (_e *MockBankOperationRepository_Expecter) UpdateStatusAndExternalID(ctx interface{}, operationId interface{}, status interface{}, externalID interface{}) *MockBankOperationRepository_UpdateStatusAndExternalID_Call {
	return &MockBankOperationRepository_UpdateStatusAndExternalID_Call{Call: _e.mock.On("UpdateStatusAndExternalID", ctx, operationId, status, externalID)}
}

func (_c *MockBankOperationRepository_UpdateStatusAndExternalID_Call) Run(run func(ctx context.Context, operationId uuid.UUID, status string, externalID string)) *MockBankOperationRepository_UpdateStatusAndExternalID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockBankOperationRepository_UpdateStatusAndExternalID_Call) Return(err error) *MockBankOperationRepository_UpdateStatusAndExternalID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBankOperationRepository_UpdateStatusAndExternalID_Call) RunAndReturn(run func(ctx context.Context, operationId uuid.UUID, status string, externalID string) error) *MockBankOperationRepository_UpdateStatusAndExternalID_Call {
	_c.Call.Return(run)
	return _c
}
