// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package services

import (
	"accounts/internal/domain/entities"
	"context"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAccountOperationRepository creates a new instance of MockAccountOperationRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAccountOperationRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAccountOperationRepository {
	mock := &MockAccountOperationRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAccountOperationRepository is an autogenerated mock type for the AccountOperationRepository type
type MockAccountOperationRepository struct {
	mock.Mock
}

type MockAccountOperationRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAccountOperationRepository) EXPECT() *MockAccountOperationRepository_Expecter {
	return &MockAccountOperationRepository_Expecter{mock: &_m.Mock}
}

// ConfirmAllByTransactionId provides a mock function for the type MockAccountOperationRepository
func (_mock *MockAccountOperationRepository) ConfirmAllByTransactionId(ctx context.Context, transactionId uuid.UUID) error {
	ret := _mock.Called(ctx, transactionId)

	if len(ret) == 0 {
		panic("no return value specified for ConfirmAllByTransactionId")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, transactionId)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAccountOperationRepository_ConfirmAllByTransactionId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ConfirmAllByTransactionId'
type MockAccountOperationRepository_ConfirmAllByTransactionId_Call struct {
	*mock.Call
}

// ConfirmAllByTransactionId is a helper method to define mock.On call
//   - ctx context.Context
//   - transactionId uuid.UUID
func (_e *MockAccountOperationRepository_Expecter) ConfirmAllByTransactionId(ctx interface{}, transactionId interface{}) *MockAccountOperationRepository_ConfirmAllByTransactionId_Call {
	return &MockAccountOperationRepository_ConfirmAllByTransactionId_Call{Call: _e.mock.On("ConfirmAllByTransactionId", ctx, transactionId)}
}

func (_c *MockAccountOperationRepository_ConfirmAllByTransactionId_Call) Run(run func(ctx context.Context, transactionId uuid.UUID)) *MockAccountOperationRepository_ConfirmAllByTransactionId_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAccountOperationRepository_ConfirmAllByTransactionId_Call) Return(err error) *MockAccountOperationRepository_ConfirmAllByTransactionId_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAccountOperationRepository_ConfirmAllByTransactionId_Call) RunAndReturn(run func(ctx context.Context, transactionId uuid.UUID) error) *MockAccountOperationRepository_ConfirmAllByTransactionId_Call {
	_c.Call.Return(run)
	return _c
}

// GetByTransactionId provides a mock function for the type MockAccountOperationRepository
func (_mock *MockAccountOperationRepository) GetByTransactionId(ctx context.Context, transactionId uuid.UUID) ([]*entities.AccountOperation, error) {
	ret := _mock.Called(ctx, transactionId)

	if len(ret) == 0 {
		panic("no return value specified for GetByTransactionId")
	}

	var r0 []*entities.AccountOperation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]*entities.AccountOperation, error)); ok {
		return returnFunc(ctx, transactionId)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) []*entities.AccountOperation); ok {
		r0 = returnFunc(ctx, transactionId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entities.AccountOperation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, transactionId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAccountOperationRepository_GetByTransactionId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByTransactionId'
type MockAccountOperationRepository_GetByTransactionId_Call struct {
	*mock.Call
}

// GetByTransactionId is a helper method to define mock.On call
//   - ctx context.Context
//   - transactionId uuid.UUID
func (_e *MockAccountOperationRepository_Expecter) GetByTransactionId(ctx interface{}, transactionId interface{}) *MockAccountOperationRepository_GetByTransactionId_Call {
	return &MockAccountOperationRepository_GetByTransactionId_Call{Call: _e.mock.On("GetByTransactionId", ctx, transactionId)}
}

func (_c *MockAccountOperationRepository_GetByTransactionId_Call) Run(run func(ctx context.Context, transactionId uuid.UUID)) *MockAccountOperationRepository_GetByTransactionId_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAccountOperationRepository_GetByTransactionId_Call) Return(accountOperations []*entities.AccountOperation, err error) *MockAccountOperationRepository_GetByTransactionId_Call {
	_c.Call.Return(accountOperations, err)
	return _c
}

func (_c *MockAccountOperationRepository_GetByTransactionId_Call) RunAndReturn(run func(ctx context.Context, transactionId uuid.UUID) ([]*entities.AccountOperation, error)) *MockAccountOperationRepository_GetByTransactionId_Call {
	_c.Call.Return(run)
	return _c
}

// GetByTransactionIdAndType provides a mock function for the type MockAccountOperationRepository
func (_mock *MockAccountOperationRepository) GetByTransactionIdAndType(ctx context.Context, transactionId uuid.UUID, operationType string) (*entities.AccountOperation, error) {
	ret := _mock.Called(ctx, transactionId, operationType)

	if len(ret) == 0 {
		panic("no return value specified for GetByTransactionIdAndType")
	}

	var r0 *entities.AccountOperation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) (*entities.AccountOperation, error)); ok {
		return returnFunc(ctx, transactionId, operationType)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) *entities.AccountOperation); ok {
		r0 = returnFunc(ctx, transactionId, operationType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.AccountOperation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, string) error); ok {
		r1 = returnFunc(ctx, transactionId, operationType)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAccountOperationRepository_GetByTransactionIdAndType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByTransactionIdAndType'
type MockAccountOperationRepository_GetByTransactionIdAndType_Call struct {
	*mock.Call
}

// GetByTransactionIdAndType is a helper method to define mock.On call
//   - ctx context.Context
//   - transactionId uuid.UUID
//   - operationType string
func (_e *MockAccountOperationRepository_Expecter) GetByTransactionIdAndType(ctx interface{}, transactionId interface{}, operationType interface{}) *MockAccountOperationRepository_GetByTransactionIdAndType_Call {
	return &MockAccountOperationRepository_GetByTransactionIdAndType_Call{Call: _e.mock.On("GetByTransactionIdAndType", ctx, transactionId, operationType)}
}

func (_c *MockAccountOperationRepository_GetByTransactionIdAndType_Call) Run(run func(ctx context.Context, transactionId uuid.UUID, operationType string)) *MockAccountOperationRepository_GetByTransactionIdAndType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAccountOperationRepository_GetByTransactionIdAndType_Call) Return(accountOperation *entities.AccountOperation, err error) *MockAccountOperationRepository_GetByTransactionIdAndType_Call {
	_c.Call.Return(accountOperation, err)
	return _c
}

func (_c *MockAccountOperationRepository_GetByTransactionIdAndType_Call) RunAndReturn(run func(ctx context.Context, transactionId uuid.UUID, operationType string) (*entities.AccountOperation, error)) *MockAccountOperationRepository_GetByTransactionIdAndType_Call {
	_c.Call.Return(run)
	return _c
}

// HasPendingByAccountId provides a mock function for the type MockAccountOperationRepository
func (_mock *MockAccountOperationRepository) HasPendingByAccountId(ctx context.Context, accountId uuid.UUID) (bool, error) {
	ret := _mock.Called(ctx, accountId)

	if len(ret) == 0 {
		panic("no return value specified for HasPendingByAccountId")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (bool, error)); ok {
		return returnFunc(ctx, accountId)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) bool); ok {
		r0 = returnFunc(ctx, accountId)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, accountId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAccountOperationRepository_HasPendingByAccountId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HasPendingByAccountId'
type MockAccountOperationRepository_HasPendingByAccountId_Call struct {
	*mock.Call
}

// HasPendingByAccountId is a helper method to define mock.On call
//   - ctx context.Context
//   - accountId uuid.UUID
func (_e *MockAccountOperationRepository_Expecter) HasPendingByAccountId(ctx interface{}, accountId interface{}) *MockAccountOperationRepository_HasPendingByAccountId_Call {
	return &MockAccountOperationRepository_HasPendingByAccountId_Call{Call: _e.mock.On("HasPendingByAccountId", ctx, accountId)}
}

func (_c *MockAccountOperationRepository_HasPendingByAccountId_Call) Run(run func(ctx context.Context, accountId uuid.UUID)) *MockAccountOperationRepository_HasPendingByAccountId_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAccountOperationRepository_HasPendingByAccountId_Call) Return(b bool, err error) *MockAccountOperationRepository_HasPendingByAccountId_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockAccountOperationRepository_HasPendingByAccountId_Call) RunAndReturn(run func(ctx context.Context, accountId uuid.UUID) (bool, error)) *MockAccountOperationRepository_HasPendingByAccountId_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type MockAccountOperationRepository
func (_mock *MockAccountOperationRepository) Save(ctx context.Context, accountOp *entities.AccountOperation) error {
	ret := _mock.Called(ctx, accountOp)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entities.AccountOperation) error); ok {
		r0 = returnFunc(ctx, accountOp)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAccountOperationRepository_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockAccountOperationRepository_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - accountOp *entities.AccountOperation
func (_e *MockAccountOperationRepository_Expecter) Save(ctx interface{}, accountOp interface{}) *MockAccountOperationRepository_Save_Call {
	return &MockAccountOperationRepository_Save_Call{Call: _e.mock.On("Save", ctx, accountOp)}
}

func (_c *MockAccountOperationRepository_Save_Call) Run(run func(ctx context.Context, accountOp *entities.AccountOperation)) *MockAccountOperationRepository_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entities.AccountOperation
		if args[1] != nil {
			arg1 = args[1].(*entities.AccountOperation)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAccountOperationRepository_Save_Call) Return(err error) *MockAccountOperationRepository_Save_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAccountOperationRepository_Save_Call) RunAndReturn(run func(ctx context.Context, accountOp *entities.AccountOperation) error) *MockAccountOperationRepository_Save_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateStatus provides a mock function for the type MockAccountOperationRepository
func (_mock *MockAccountOperationRepository) UpdateStatus(ctx context.Context, operation uuid.UUID, status string) error {
	ret := _mock.Called(ctx, operation, status)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatus")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) error); ok {
		r0 = returnFunc(ctx, operation, status)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAccountOperationRepository_UpdateStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateStatus'
type MockAccountOperationRepository_UpdateStatus_Call struct {
	*mock.Call
}

// UpdateStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - operation uuid.UUID
//   - status string
func (_e *MockAccountOperationRepository_Expecter) UpdateStatus(ctx interface{}, operation interface{}, status interface{}) *MockAccountOperationRepository_UpdateStatus_Call {
	return &MockAccountOperationRepository_UpdateStatus_Call{Call: _e.mock.On("UpdateStatus", ctx, operation, status)}
}

func (_c *MockAccountOperationRepository_UpdateStatus_Call) Run(run func(ctx context.Context, operation uuid.UUID, status string)) *MockAccountOperationRepository_UpdateStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAccountOperationRepository_UpdateStatus_Call) Return(err error) *MockAccountOperationRepository_UpdateStatus_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAccountOperationRepository_UpdateStatus_Call) RunAndReturn(run func(ctx context.Context, operation uuid.UUID, status string) error) *MockAccountOperationRepository_UpdateStatus_Call {
	_c.Call.Return(run)
	return _c
}
