// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package services

import (
	"accounts/internal/domain/entities"
	"context"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockBankAccountRepository creates a new instance of MockBankAccountRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBankAccountRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBankAccountRepository {
	mock := &MockBankAccountRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockBankAccountRepository is an autogenerated mock type for the BankAccountRepository type
type MockBankAccountRepository struct {
	mock.Mock
}

type MockBankAccountRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBankAccountRepository) EXPECT() *MockBankAccountRepository_Expecter {
	return &MockBankAccountRepository_Expecter{mock: &_m.Mock}
}

// GetByCompanyId provides a mock function for the type MockBankAccountRepository
func (_mock *MockBankAccountRepository) GetByCompanyId(ctx context.Context, companyId uuid.UUID) ([]*entities.BankAccount, error) {
	ret := _mock.Called(ctx, companyId)

	if len(ret) == 0 {
		panic("no return value specified for GetByCompanyId")
	}

	var r0 []*entities.BankAccount
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]*entities.BankAccount, error)); ok {
		return returnFunc(ctx, companyId)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) []*entities.BankAccount); ok {
		r0 = returnFunc(ctx, companyId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entities.BankAccount)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, companyId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBankAccountRepository_GetByCompanyId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByCompanyId'
type MockBankAccountRepository_GetByCompanyId_Call struct {
	*mock.Call
}

// GetByCompanyId is a helper method to define mock.On call
//   - ctx context.Context
//   - companyId uuid.UUID
func (_e *MockBankAccountRepository_Expecter) GetByCompanyId(ctx interface{}, companyId interface{}) *MockBankAccountRepository_GetByCompanyId_Call {
	return &MockBankAccountRepository_GetByCompanyId_Call{Call: _e.mock.On("GetByCompanyId", ctx, companyId)}
}

func (_c *MockBankAccountRepository_GetByCompanyId_Call) Run(run func(ctx context.Context, companyId uuid.UUID)) *MockBankAccountRepository_GetByCompanyId_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBankAccountRepository_GetByCompanyId_Call) Return(bankAccounts []*entities.BankAccount, err error) *MockBankAccountRepository_GetByCompanyId_Call {
	_c.Call.Return(bankAccounts, err)
	return _c
}

func (_c *MockBankAccountRepository_GetByCompanyId_Call) RunAndReturn(run func(ctx context.Context, companyId uuid.UUID) ([]*entities.BankAccount, error)) *MockBankAccountRepository_GetByCompanyId_Call {
	_c.Call.Return(run)
	return _c
}

// GetById provides a mock function for the type MockBankAccountRepository
func (_mock *MockBankAccountRepository) GetById(ctx context.Context, id uuid.UUID) (*entities.BankAccount, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetById")
	}

	var r0 *entities.BankAccount
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*entities.BankAccount, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *entities.BankAccount); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.BankAccount)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBankAccountRepository_GetById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetById'
type MockBankAccountRepository_GetById_Call struct {
	*mock.Call
}

// GetById is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockBankAccountRepository_Expecter) GetById(ctx interface{}, id interface{}) *MockBankAccountRepository_GetById_Call {
	return &MockBankAccountRepository_GetById_Call{Call: _e.mock.On("GetById", ctx, id)}
}

func (_c *MockBankAccountRepository_GetById_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockBankAccountRepository_GetById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBankAccountRepository_GetById_Call) Return(bankAccount *entities.BankAccount, err error) *MockBankAccountRepository_GetById_Call {
	_c.Call.Return(bankAccount, err)
	return _c
}

func (_c *MockBankAccountRepository_GetById_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (*entities.BankAccount, error)) *MockBankAccountRepository_GetById_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type MockBankAccountRepository
func (_mock *MockBankAccountRepository) Save(ctx context.Context, account *entities.BankAccount) error {
	ret := _mock.Called(ctx, account)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entities.BankAccount) error); ok {
		r0 = returnFunc(ctx, account)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBankAccountRepository_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockBankAccountRepository_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - account *entities.BankAccount
func (_e *MockBankAccountRepository_Expecter) Save(ctx interface{}, account interface{}) *MockBankAccountRepository_Save_Call {
	return &MockBankAccountRepository_Save_Call{Call: _e.mock.On("Save", ctx, account)}
}

func (_c *MockBankAccountRepository_Save_Call) Run(run func(ctx context.Context, account *entities.BankAccount)) *MockBankAccountRepository_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entities.BankAccount
		if args[1] != nil {
			arg1 = args[1].(*entities.BankAccount)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBankAccountRepository_Save_Call) Return(err error) *MockBankAccountRepository_Save_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBankAccountRepository_Save_Call) RunAndReturn(run func(ctx context.Context, account *entities.BankAccount) error) *MockBankAccountRepository_Save_Call {
	_c.Call.Return(run)
	return _c
}
