// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package services

import (
	"accounts/internal/domain/entities"
	"context"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAccountRepository creates a new instance of MockAccountRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAccountRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAccountRepository {
	mock := &MockAccountRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAccountRepository is an autogenerated mock type for the AccountRepository type
type MockAccountRepository struct {
	mock.Mock
}

type MockAccountRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAccountRepository) EXPECT() *MockAccountRepository_Expecter {
	return &MockAccountRepository_Expecter{mock: &_m.Mock}
}

// GetByCompanyId provides a mock function for the type MockAccountRepository
func (_mock *MockAccountRepository) GetByCompanyId(ctx context.Context, companyId uuid.UUID) ([]*entities.Account, error) {
	ret := _mock.Called(ctx, companyId)

	if len(ret) == 0 {
		panic("no return value specified for GetByCompanyId")
	}

	var r0 []*entities.Account
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]*entities.Account, error)); ok {
		return returnFunc(ctx, companyId)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) []*entities.Account); ok {
		r0 = returnFunc(ctx, companyId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entities.Account)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, companyId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAccountRepository_GetByCompanyId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByCompanyId'
type MockAccountRepository_GetByCompanyId_Call struct {
	*mock.Call
}

// GetByCompanyId is a helper method to define mock.On call
//   - ctx context.Context
//   - companyId uuid.UUID
func (_e *MockAccountRepository_Expecter) GetByCompanyId(ctx interface{}, companyId interface{}) *MockAccountRepository_GetByCompanyId_Call {
	return &MockAccountRepository_GetByCompanyId_Call{Call: _e.mock.On("GetByCompanyId", ctx, companyId)}
}

func (_c *MockAccountRepository_GetByCompanyId_Call) Run(run func(ctx context.Context, companyId uuid.UUID)) *MockAccountRepository_GetByCompanyId_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAccountRepository_GetByCompanyId_Call) Return(accounts []*entities.Account, err error) *MockAccountRepository_GetByCompanyId_Call {
	_c.Call.Return(accounts, err)
	return _c
}

func (_c *MockAccountRepository_GetByCompanyId_Call) RunAndReturn(run func(ctx context.Context, companyId uuid.UUID) ([]*entities.Account, error)) *MockAccountRepository_GetByCompanyId_Call {
	_c.Call.Return(run)
	return _c
}

// GetById provides a mock function for the type MockAccountRepository
func (_mock *MockAccountRepository) GetById(ctx context.Context, id uuid.UUID) (*entities.Account, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetById")
	}

	var r0 *entities.Account
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*entities.Account, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *entities.Account); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Account)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAccountRepository_GetById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetById'
type MockAccountRepository_GetById_Call struct {
	*mock.Call
}

// GetById is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockAccountRepository_Expecter) GetById(ctx interface{}, id interface{}) *MockAccountRepository_GetById_Call {
	return &MockAccountRepository_GetById_Call{Call: _e.mock.On("GetById", ctx, id)}
}

func (_c *MockAccountRepository_GetById_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockAccountRepository_GetById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAccountRepository_GetById_Call) Return(account *entities.Account, err error) *MockAccountRepository_GetById_Call {
	_c.Call.Return(account, err)
	return _c
}

func (_c *MockAccountRepository_GetById_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (*entities.Account, error)) *MockAccountRepository_GetById_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type MockAccountRepository
func (_mock *MockAccountRepository) Save(ctx context.Context, account *entities.Account) error {
	ret := _mock.Called(ctx, account)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entities.Account) error); ok {
		r0 = returnFunc(ctx, account)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAccountRepository_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockAccountRepository_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - account *entities.Account
func (_e *MockAccountRepository_Expecter) Save(ctx interface{}, account interface{}) *MockAccountRepository_Save_Call {
	return &MockAccountRepository_Save_Call{Call: _e.mock.On("Save", ctx, account)}
}

func (_c *MockAccountRepository_Save_Call) Run(run func(ctx context.Context, account *entities.Account)) *MockAccountRepository_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entities.Account
		if args[1] != nil {
			arg1 = args[1].(*entities.Account)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAccountRepository_Save_Call) Return(err error) *MockAccountRepository_Save_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAccountRepository_Save_Call) RunAndReturn(run func(ctx context.Context, account *entities.Account) error) *MockAccountRepository_Save_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateBalance provides a mock function for the type MockAccountRepository
func (_mock *MockAccountRepository) UpdateBalance(ctx context.Context, accountId uuid.UUID, amount int64) error {
	ret := _mock.Called(ctx, accountId, amount)

	if len(ret) == 0 {
		panic("no return value specified for UpdateBalance")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, int64) error); ok {
		r0 = returnFunc(ctx, accountId, amount)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAccountRepository_UpdateBalance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateBalance'
type MockAccountRepository_UpdateBalance_Call struct {
	*mock.Call
}

// UpdateBalance is a helper method to define mock.On call
//   - ctx context.Context
//   - accountId uuid.UUID
//   - amount int64
func (_e *MockAccountRepository_Expecter) UpdateBalance(ctx interface{}, accountId interface{}, amount interface{}) *MockAccountRepository_UpdateBalance_Call {
	return &MockAccountRepository_UpdateBalance_Call{Call: _e.mock.On("UpdateBalance", ctx, accountId, amount)}
}

func (_c *MockAccountRepository_UpdateBalance_Call) Run(run func(ctx context.Context, accountId uuid.UUID, amount int64)) *MockAccountRepository_UpdateBalance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAccountRepository_UpdateBalance_Call) Return(err error) *MockAccountRepository_UpdateBalance_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAccountRepository_UpdateBalance_Call) RunAndReturn(run func(ctx context.Context, accountId uuid.UUID, amount int64) error) *MockAccountRepository_UpdateBalance_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateStatus provides a mock function for the type MockAccountRepository
func (_mock *MockAccountRepository) UpdateStatus(ctx context.Context, accountId uuid.UUID, status string) error {
	ret := _mock.Called(ctx, accountId, status)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatus")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) error); ok {
		r0 = returnFunc(ctx, accountId, status)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAccountRepository_UpdateStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateStatus'
type MockAccountRepository_UpdateStatus_Call struct {
	*mock.Call
}

// UpdateStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - accountId uuid.UUID
//   - status string
func (_e *MockAccountRepository_Expecter) UpdateStatus(ctx interface{}, accountId interface{}, status interface{}) *MockAccountRepository_UpdateStatus_Call {
	return &MockAccountRepository_UpdateStatus_Call{Call: _e.mock.On("UpdateStatus", ctx, accountId, status)}
}

func (_c *MockAccountRepository_UpdateStatus_Call) Run(run func(ctx context.Context, accountId uuid.UUID, status string)) *MockAccountRepository_UpdateStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAccountRepository_UpdateStatus_Call) Return(err error) *MockAccountRepository_UpdateStatus_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAccountRepository_UpdateStatus_Call) RunAndReturn(run func(ctx context.Context, accountId uuid.UUID, status string) error) *MockAccountRepository_UpdateStatus_Call {
	_c.Call.Return(run)
	return _c
}
