// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package services

import (
	"accounts/internal/domain/entities"
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockBankGateway creates a new instance of MockBankGateway. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBankGateway(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBankGateway {
	mock := &MockBankGateway{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockBankGateway is an autogenerated mock type for the BankGateway type
type MockBankGateway struct {
	mock.Mock
}

type MockBankGateway_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBankGateway) EXPECT() *MockBankGateway_Expecter {
	return &MockBankGateway_Expecter{mock: &_m.Mock}
}

// Deposit provides a mock function for the type MockBankGateway
func (_mock *MockBankGateway) Deposit(ctx context.Context, bankAccount *entities.BankAccount, amount int64, idempotencyKey string) (string, error) {
	ret := _mock.Called(ctx, bankAccount, amount, idempotencyKey)

	if len(ret) == 0 {
		panic("no return value specified for Deposit")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entities.BankAccount, int64, string) (string, error)); ok {
		return returnFunc(ctx, bankAccount, amount, idempotencyKey)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entities.BankAccount, int64, string) string); ok {
		r0 = returnFunc(ctx, bankAccount, amount, idempotencyKey)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *entities.BankAccount, int64, string) error); ok {
		r1 = returnFunc(ctx, bankAccount, amount, idempotencyKey)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBankGateway_Deposit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Deposit'
type MockBankGateway_Deposit_Call struct {
	*mock.Call
}

// Deposit is a helper method to define mock.On call
//   - ctx context.Context
//   - bankAccount *entities.BankAccount
//   - amount int64
//   - idempotencyKey string
func (_e *MockBankGateway_Expecter) Deposit(ctx interface{}, bankAccount interface{}, amount interface{}, idempotencyKey interface{}) *MockBankGateway_Deposit_Call {
	return &MockBankGateway_Deposit_Call{Call: _e.mock.On("Deposit", ctx, bankAccount, amount, idempotencyKey)}
}

func (_c *MockBankGateway_Deposit_Call) Run(run func(ctx context.Context, bankAccount *entities.BankAccount, amount int64, idempotencyKey string)) *MockBankGateway_Deposit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entities.BankAccount
		if args[1] != nil {
			arg1 = args[1].(*entities.BankAccount)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockBankGateway_Deposit_Call) Return(s string, err error) *MockBankGateway_Deposit_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockBankGateway_Deposit_Call) RunAndReturn(run func(ctx context.Context, bankAccount *entities.BankAccount, amount int64, idempotencyKey string) (string, error)) *MockBankGateway_Deposit_Call {
	_c.Call.Return(run)
	return _c
}

// Withdraw provides a mock function for the type MockBankGateway
func (_mock *MockBankGateway) Withdraw(ctx context.Context, bankAccount *entities.BankAccount, amount int64, idempotencyKey string) (string, error) {
	ret := _mock.Called(ctx, bankAccount, amount, idempotencyKey)

	if len(ret) == 0 {
		panic("no return value specified for Withdraw")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entities.BankAccount, int64, string) (string, error)); ok {
		return returnFunc(ctx, bankAccount, amount, idempotencyKey)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entities.BankAccount, int64, string) string); ok {
		r0 = returnFunc(ctx, bankAccount, amount, idempotencyKey)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *entities.BankAccount, int64, string) error); ok {
		r1 = returnFunc(ctx, bankAccount, amount, idempotencyKey)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBankGateway_Withdraw_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Withdraw'
type MockBankGateway_Withdraw_Call struct {
	*mock.Call
}

// Withdraw is a helper method to define mock.On call
//   - ctx context.Context
//   - bankAccount *entities.BankAccount
//   - amount int64
//   - idempotencyKey string
func (_e *MockBankGateway_Expecter) Withdraw(ctx interface{}, bankAccount interface{}, amount interface{}, idempotencyKey interface{}) *MockBankGateway_Withdraw_Call {
	return &MockBankGateway_Withdraw_Call{Call: _e.mock.On("Withdraw", ctx, bankAccount, amount, idempotencyKey)}
}

func (_c *MockBankGateway_Withdraw_Call) Run(run func(ctx context.Context, bankAccount *entities.BankAccount, amount int64, idempotencyKey string)) *MockBankGateway_Withdraw_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entities.BankAccount
		if args[1] != nil {
			arg1 = args[1].(*entities.BankAccount)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockBankGateway_Withdraw_Call) Return(s string, err error) *MockBankGateway_Withdraw_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockBankGateway_Withdraw_Call) RunAndReturn(run func(ctx context.Context, bankAccount *entities.BankAccount, amount int64, idempotencyKey string) (string, error)) *MockBankGateway_Withdraw_Call {
	_c.Call.Return(run)
	return _c
}
