// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package services

import (
	"shared/pkg/auth"

	mock "github.com/stretchr/testify/mock"
)

// NewMockTokenValidator creates a new instance of MockTokenValidator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTokenValidator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTokenValidator {
	mock := &MockTokenValidator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTokenValidator is an autogenerated mock type for the TokenValidator type
type MockTokenValidator struct {
	mock.Mock
}

type MockTokenValidator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTokenValidator) EXPECT() *MockTokenValidator_Expecter {
	return &MockTokenValidator_Expecter{mock: &_m.Mock}
}

// Validate provides a mock function for the type MockTokenValidator
func (_mock *MockTokenValidator) Validate(tokenString string) (*auth.AccessClaims, error) {
	ret := _mock.Called(tokenString)

	if len(ret) == 0 {
		panic("no return value specified for Validate")
	}

	var r0 *auth.AccessClaims
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*auth.AccessClaims, error)); ok {
		return returnFunc(tokenString)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *auth.AccessClaims); ok {
		r0 = returnFunc(tokenString)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*auth.AccessClaims)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(tokenString)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTokenValidator_Validate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Validate'
type MockTokenValidator_Validate_Call struct {
	*mock.Call
}

// Validate is a helper method to define mock.On call
//   - tokenString string
func (_e *MockTokenValidator_Expecter) Validate(tokenString interface{}) *MockTokenValidator_Validate_Call {
	return &MockTokenValidator_Validate_Call{Call: _e.mock.On("Validate", tokenString)}
}

func (_c *MockTokenValidator_Validate_Call) Run(run func(tokenString string)) *MockTokenValidator_Validate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTokenValidator_Validate_Call) Return(accessClaims *auth.AccessClaims, err error) *MockTokenValidator_Validate_Call {
	_c.Call.Return(accessClaims, err)
	return _c
}

func (_c *MockTokenValidator_Validate_Call) RunAndReturn(run func(tokenString string) (*auth.AccessClaims, error)) *MockTokenValidator_Validate_Call {
	_c.Call.Return(run)
	return _c
}
