// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package services

import (
	"context"
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewMockBlackListRepository creates a new instance of MockBlackListRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBlackListRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBlackListRepository {
	mock := &MockBlackListRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockBlackListRepository is an autogenerated mock type for the BlackListRepository type
type MockBlackListRepository struct {
	mock.Mock
}

type MockBlackListRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBlackListRepository) EXPECT() *MockBlackListRepository_Expecter {
	return &MockBlackListRepository_Expecter{mock: &_m.Mock}
}

// Exists provides a mock function for the type MockBlackListRepository
func (_mock *MockBlackListRepository) Exists(ctx context.Context, tokenID string) (bool, error) {
	ret := _mock.Called(ctx, tokenID)

	if len(ret) == 0 {
		panic("no return value specified for Exists")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return returnFunc(ctx, tokenID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = returnFunc(ctx, tokenID)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, tokenID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBlackListRepository_Exists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exists'
type MockBlackListRepository_Exists_Call struct {
	*mock.Call
}

// Exists is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenID string
func (_e *MockBlackListRepository_Expecter) Exists(ctx interface{}, tokenID interface{}) *MockBlackListRepository_Exists_Call {
	return &MockBlackListRepository_Exists_Call{Call: _e.mock.On("Exists", ctx, tokenID)}
}

func (_c *MockBlackListRepository_Exists_Call) Run(run func(ctx context.Context, tokenID string)) *MockBlackListRepository_Exists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBlackListRepository_Exists_Call) Return(b bool, err error) *MockBlackListRepository_Exists_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockBlackListRepository_Exists_Call) RunAndReturn(run func(ctx context.Context, tokenID string) (bool, error)) *MockBlackListRepository_Exists_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type MockBlackListRepository
func (_mock *MockBlackListRepository) Save(ctx context.Context, tokenID string, tokenTTL time.Duration) error {
	ret := _mock.Called(ctx, tokenID, tokenTTL)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Duration) error); ok {
		r0 = returnFunc(ctx, tokenID, tokenTTL)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBlackListRepository_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockBlackListRepository_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenID string
//   - tokenTTL time.Duration
func (_e *MockBlackListRepository_Expecter) Save(ctx interface{}, tokenID interface{}, tokenTTL interface{}) *MockBlackListRepository_Save_Call {
	return &MockBlackListRepository_Save_Call{Call: _e.mock.On("Save", ctx, tokenID, tokenTTL)}
}

func (_c *MockBlackListRepository_Save_Call) Run(run func(ctx context.Context, tokenID string, tokenTTL time.Duration)) *MockBlackListRepository_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 time.Duration
		if args[2] != nil {
			arg2 = args[2].(time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockBlackListRepository_Save_Call) Return(err error) *MockBlackListRepository_Save_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBlackListRepository_Save_Call) RunAndReturn(run func(ctx context.Context, tokenID string, tokenTTL time.Duration) error) *MockBlackListRepository_Save_Call {
	_c.Call.Return(run)
	return _c
}
