// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package services

import (
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockTokenService creates a new instance of MockTokenService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTokenService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTokenService {
	mock := &MockTokenService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTokenService is an autogenerated mock type for the TokenService type
type MockTokenService struct {
	mock.Mock
}

type MockTokenService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTokenService) EXPECT() *MockTokenService_Expecter {
	return &MockTokenService_Expecter{mock: &_m.Mock}
}

// Generate provides a mock function for the type MockTokenService
func (_mock *MockTokenService) Generate(userId uuid.UUID, companyId uuid.UUID, role string) (string, error) {
	ret := _mock.Called(userId, companyId, role)

	if len(ret) == 0 {
		panic("no return value specified for Generate")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID, uuid.UUID, string) (string, error)); ok {
		return returnFunc(userId, companyId, role)
	}
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID, uuid.UUID, string) string); ok {
		r0 = returnFunc(userId, companyId, role)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(uuid.UUID, uuid.UUID, string) error); ok {
		r1 = returnFunc(userId, companyId, role)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTokenService_Generate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Generate'
type MockTokenService_Generate_Call struct {
	*mock.Call
}

// Generate is a helper method to define mock.On call
//   - userId uuid.UUID
//   - companyId uuid.UUID
//   - role string
func (_e *MockTokenService_Expecter) Generate(userId interface{}, companyId interface{}, role interface{}) *MockTokenService_Generate_Call {
	return &MockTokenService_Generate_Call{Call: _e.mock.On("Generate", userId, companyId, role)}
}

func (_c *MockTokenService_Generate_Call) Run(run func(userId uuid.UUID, companyId uuid.UUID, role string)) *MockTokenService_Generate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uuid.UUID
		if args[0] != nil {
			arg0 = args[0].(uuid.UUID)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTokenService_Generate_Call) Return(s string, err error) *MockTokenService_Generate_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockTokenService_Generate_Call) RunAndReturn(run func(userId uuid.UUID, companyId uuid.UUID, role string) (string, error)) *MockTokenService_Generate_Call {
	_c.Call.Return(run)
	return _c
}
