// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package services

import (
	"auth/internal/domain/entities"
	"context"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockCompanyRepository creates a new instance of MockCompanyRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCompanyRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCompanyRepository {
	mock := &MockCompanyRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCompanyRepository is an autogenerated mock type for the CompanyRepository type
type MockCompanyRepository struct {
	mock.Mock
}

type MockCompanyRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCompanyRepository) EXPECT() *MockCompanyRepository_Expecter {
	return &MockCompanyRepository_Expecter{mock: &_m.Mock}
}

// GetById provides a mock function for the type MockCompanyRepository
func (_mock *MockCompanyRepository) GetById(ctx context.Context, companyId uuid.UUID) (*entities.Company, error) {
	ret := _mock.Called(ctx, companyId)

	if len(ret) == 0 {
		panic("no return value specified for GetById")
	}

	var r0 *entities.Company
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*entities.Company, error)); ok {
		return returnFunc(ctx, companyId)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *entities.Company); ok {
		r0 = returnFunc(ctx, companyId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Company)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, companyId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCompanyRepository_GetById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetById'
type MockCompanyRepository_GetById_Call struct {
	*mock.Call
}

// GetById is a helper method to define mock.On call
//   - ctx context.Context
//   - companyId uuid.UUID
func (_e *MockCompanyRepository_Expecter) GetById(ctx interface{}, companyId interface{}) *MockCompanyRepository_GetById_Call {
	return &MockCompanyRepository_GetById_Call{Call: _e.mock.On("GetById", ctx, companyId)}
}

func (_c *MockCompanyRepository_GetById_Call) Run(run func(ctx context.Context, companyId uuid.UUID)) *MockCompanyRepository_GetById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCompanyRepository_GetById_Call) Return(company *entities.Company, err error) *MockCompanyRepository_GetById_Call {
	_c.Call.Return(company, err)
	return _c
}

func (_c *MockCompanyRepository_GetById_Call) RunAndReturn(run func(ctx context.Context, companyId uuid.UUID) (*entities.Company, error)) *MockCompanyRepository_GetById_Call {
	_c.Call.Return(run)
	return _c
}

// GetByInviteCode provides a mock function for the type MockCompanyRepository
func (_mock *MockCompanyRepository) GetByInviteCode(ctx context.Context, inviteCode string) (*entities.Company, error) {
	ret := _mock.Called(ctx, inviteCode)

	if len(ret) == 0 {
		panic("no return value specified for GetByInviteCode")
	}

	var r0 *entities.Company
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*entities.Company, error)); ok {
		return returnFunc(ctx, inviteCode)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *entities.Company); ok {
		r0 = returnFunc(ctx, inviteCode)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Company)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, inviteCode)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCompanyRepository_GetByInviteCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByInviteCode'
type MockCompanyRepository_GetByInviteCode_Call struct {
	*mock.Call
}

// GetByInviteCode is a helper method to define mock.On call
//   - ctx context.Context
//   - inviteCode string
func (_e *MockCompanyRepository_Expecter) GetByInviteCode(ctx interface{}, inviteCode interface{}) *MockCompanyRepository_GetByInviteCode_Call {
	return &MockCompanyRepository_GetByInviteCode_Call{Call: _e.mock.On("GetByInviteCode", ctx, inviteCode)}
}

func (_c *MockCompanyRepository_GetByInviteCode_Call) Run(run func(ctx context.Context, inviteCode string)) *MockCompanyRepository_GetByInviteCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCompanyRepository_GetByInviteCode_Call) Return(company *entities.Company, err error) *MockCompanyRepository_GetByInviteCode_Call {
	_c.Call.Return(company, err)
	return _c
}

func (_c *MockCompanyRepository_GetByInviteCode_Call) RunAndReturn(run func(ctx context.Context, inviteCode string) (*entities.Company, error)) *MockCompanyRepository_GetByInviteCode_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type MockCompanyRepository
func (_mock *MockCompanyRepository) Save(ctx context.Context, company *entities.Company) error {
	ret := _mock.Called(ctx, company)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entities.Company) error); ok {
		r0 = returnFunc(ctx, company)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCompanyRepository_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockCompanyRepository_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - company *entities.Company
func (_e *MockCompanyRepository_Expecter) Save(ctx interface{}, company interface{}) *MockCompanyRepository_Save_Call {
	return &MockCompanyRepository_Save_Call{Call: _e.mock.On("Save", ctx, company)}
}

func (_c *MockCompanyRepository_Save_Call) Run(run func(ctx context.Context, company *entities.Company)) *MockCompanyRepository_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entities.Company
		if args[1] != nil {
			arg1 = args[1].(*entities.Company)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCompanyRepository_Save_Call) Return(err error) *MockCompanyRepository_Save_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCompanyRepository_Save_Call) RunAndReturn(run func(ctx context.Context, company *entities.Company) error) *MockCompanyRepository_Save_Call {
	_c.Call.Return(run)
	return _c
}
