env: "local"

db:
  host: postgres-transactions
  port: 5432
  name: transaction_service
  ssl_mode: disable
  connect_timeout: 3s
  max_retries_time: 10s

grpc:
  port: 50051
  timeout: 5s

grpc_client:
  addr: account_service:50051

kafka:
  brokers: kafka:29092
  write_timeout: 5s

outbox:
  interval: 10s
  batch_size: 10

recover:
  interval: 10s
  stale_after: 30s