// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package services

import (
	"context"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAccountClient creates a new instance of MockAccountClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAccountClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAccountClient {
	mock := &MockAccountClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAccountClient is an autogenerated mock type for the AccountClient type
type MockAccountClient struct {
	mock.Mock
}

type MockAccountClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAccountClient) EXPECT() *MockAccountClient_Expecter {
	return &MockAccountClient_Expecter{mock: &_m.Mock}
}

// CancelOperation provides a mock function for the type MockAccountClient
func (_mock *MockAccountClient) CancelOperation(ctx context.Context, txId uuid.UUID) error {
	ret := _mock.Called(ctx, txId)

	if len(ret) == 0 {
		panic("no return value specified for CancelOperation")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, txId)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAccountClient_CancelOperation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CancelOperation'
type MockAccountClient_CancelOperation_Call struct {
	*mock.Call
}

// CancelOperation is a helper method to define mock.On call
//   - ctx context.Context
//   - txId uuid.UUID
func (_e *MockAccountClient_Expecter) CancelOperation(ctx interface{}, txId interface{}) *MockAccountClient_CancelOperation_Call {
	return &MockAccountClient_CancelOperation_Call{Call: _e.mock.On("CancelOperation", ctx, txId)}
}

func (_c *MockAccountClient_CancelOperation_Call) Run(run func(ctx context.Context, txId uuid.UUID)) *MockAccountClient_CancelOperation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAccountClient_CancelOperation_Call) Return(err error) *MockAccountClient_CancelOperation_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAccountClient_CancelOperation_Call) RunAndReturn(run func(ctx context.Context, txId uuid.UUID) error) *MockAccountClient_CancelOperation_Call {
	_c.Call.Return(run)
	return _c
}

// ConfirmOperation provides a mock function for the type MockAccountClient
func (_mock *MockAccountClient) ConfirmOperation(ctx context.Context, txId uuid.UUID) error {
	ret := _mock.Called(ctx, txId)

	if len(ret) == 0 {
		panic("no return value specified for ConfirmOperation")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, txId)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAccountClient_ConfirmOperation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ConfirmOperation'
type MockAccountClient_ConfirmOperation_Call struct {
	*mock.Call
}

// ConfirmOperation is a helper method to define mock.On call
//   - ctx context.Context
//   - txId uuid.UUID
func (_e *MockAccountClient_Expecter) ConfirmOperation(ctx interface{}, txId interface{}) *MockAccountClient_ConfirmOperation_Call {
	return &MockAccountClient_ConfirmOperation_Call{Call: _e.mock.On("ConfirmOperation", ctx, txId)}
}

func (_c *MockAccountClient_ConfirmOperation_Call) Run(run func(ctx context.Context, txId uuid.UUID)) *MockAccountClient_ConfirmOperation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAccountClient_ConfirmOperation_Call) Return(err error) *MockAccountClient_ConfirmOperation_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAccountClient_ConfirmOperation_Call) RunAndReturn(run func(ctx context.Context, txId uuid.UUID) error) *MockAccountClient_ConfirmOperation_Call {
	_c.Call.Return(run)
	return _c
}

// ReserveDeposit provides a mock function for the type MockAccountClient
func (_mock *MockAccountClient) ReserveDeposit(ctx context.Context, accountId uuid.UUID, txId uuid.UUID, amount int64) error {
	ret := _mock.Called(ctx, accountId, txId, amount)

	if len(ret) == 0 {
		panic("no return value specified for ReserveDeposit")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, int64) error); ok {
		r0 = returnFunc(ctx, accountId, txId, amount)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAccountClient_ReserveDeposit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReserveDeposit'
type MockAccountClient_ReserveDeposit_Call struct {
	*mock.Call
}

// ReserveDeposit is a helper method to define mock.On call
//   - ctx context.Context
//   - accountId uuid.UUID
//   - txId uuid.UUID
//   - amount int64
func (_e *MockAccountClient_Expecter) ReserveDeposit(ctx interface{}, accountId interface{}, txId interface{}, amount interface{}) *MockAccountClient_ReserveDeposit_Call {
	return &MockAccountClient_ReserveDeposit_Call{Call: _e.mock.On("ReserveDeposit", ctx, accountId, txId, amount)}
}

func (_c *MockAccountClient_ReserveDeposit_Call) Run(run func(ctx context.Context, accountId uuid.UUID, txId uuid.UUID, amount int64)) *MockAccountClient_ReserveDeposit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		var arg3 int64
		if args[3] != nil {
			arg3 = args[3].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockAccountClient_ReserveDeposit_Call) Return(err error) *MockAccountClient_ReserveDeposit_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAccountClient_ReserveDeposit_Call) RunAndReturn(run func(ctx context.Context, accountId uuid.UUID, txId uuid.UUID, amount int64) error) *MockAccountClient_ReserveDeposit_Call {
	_c.Call.Return(run)
	return _c
}

// ReserveWithdraw provides a mock function for the type MockAccountClient
func (_mock *MockAccountClient) ReserveWithdraw(ctx context.Context, accountId uuid.UUID, txId uuid.UUID, amount int64) error {
	ret := _mock.Called(ctx, accountId, txId, amount)

	if len(ret) == 0 {
		panic("no return value specified for ReserveWithdraw")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, int64) error); ok {
		r0 = returnFunc(ctx, accountId, txId, amount)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAccountClient_ReserveWithdraw_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReserveWithdraw'
type MockAccountClient_ReserveWithdraw_Call struct {
	*mock.Call
}

// ReserveWithdraw is a helper method to define mock.On call
//   - ctx context.Context
//   - accountId uuid.UUID
//   - txId uuid.UUID
//   - amount int64
func (_e *MockAccountClient_Expecter) ReserveWithdraw(ctx interface{}, accountId interface{}, txId interface{}, amount interface{}) *MockAccountClient_ReserveWithdraw_Call {
	return &MockAccountClient_ReserveWithdraw_Call{Call: _e.mock.On("ReserveWithdraw", ctx, accountId, txId, amount)}
}

func (_c *MockAccountClient_ReserveWithdraw_Call) Run(run func(ctx context.Context, accountId uuid.UUID, txId uuid.UUID, amount int64)) *MockAccountClient_ReserveWithdraw_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		var arg3 int64
		if args[3] != nil {
			arg3 = args[3].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockAccountClient_ReserveWithdraw_Call) Return(err error) *MockAccountClient_ReserveWithdraw_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAccountClient_ReserveWithdraw_Call) RunAndReturn(run func(ctx context.Context, accountId uuid.UUID, txId uuid.UUID, amount int64) error) *MockAccountClient_ReserveWithdraw_Call {
	_c.Call.Return(run)
	return _c
}
