// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package service

import (
	"context"
	"time"
	"transactions/internal/domain/entities"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockTransactionRepository creates a new instance of MockTransactionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTransactionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTransactionRepository {
	mock := &MockTransactionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTransactionRepository is an autogenerated mock type for the TransactionRepository type
type MockTransactionRepository struct {
	mock.Mock
}

type MockTransactionRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTransactionRepository) EXPECT() *MockTransactionRepository_Expecter {
	return &MockTransactionRepository_Expecter{mock: &_m.Mock}
}

// GetByAccountId provides a mock function for the type MockTransactionRepository
func (_mock *MockTransactionRepository) GetByAccountId(ctx context.Context, accountId uuid.UUID) ([]*entities.Transaction, error) {
	ret := _mock.Called(ctx, accountId)

	if len(ret) == 0 {
		panic("no return value specified for GetByAccountId")
	}

	var r0 []*entities.Transaction
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]*entities.Transaction, error)); ok {
		return returnFunc(ctx, accountId)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) []*entities.Transaction); ok {
		r0 = returnFunc(ctx, accountId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entities.Transaction)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, accountId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTransactionRepository_GetByAccountId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByAccountId'
type MockTransactionRepository_GetByAccountId_Call struct {
	*mock.Call
}

// GetByAccountId is a helper method to define mock.On call
//   - ctx context.Context
//   - accountId uuid.UUID
func (_e *MockTransactionRepository_Expecter) GetByAccountId(ctx interface{}, accountId interface{}) *MockTransactionRepository_GetByAccountId_Call {
	return &MockTransactionRepository_GetByAccountId_Call{Call: _e.mock.On("GetByAccountId", ctx, accountId)}
}

func (_c *MockTransactionRepository_GetByAccountId_Call) Run(run func(ctx context.Context, accountId uuid.UUID)) *MockTransactionRepository_GetByAccountId_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTransactionRepository_GetByAccountId_Call) Return(transactions []*entities.Transaction, err error) *MockTransactionRepository_GetByAccountId_Call {
	_c.Call.Return(transactions, err)
	return _c
}

func (_c *MockTransactionRepository_GetByAccountId_Call) RunAndReturn(run func(ctx context.Context, accountId uuid.UUID) ([]*entities.Transaction, error)) *MockTransactionRepository_GetByAccountId_Call {
	_c.Call.Return(run)
	return _c
}

// GetById provides a mock function for the type MockTransactionRepository
func (_mock *MockTransactionRepository) GetById(ctx context.Context, id uuid.UUID) (*entities.Transaction, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetById")
	}

	var r0 *entities.Transaction
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*entities.Transaction, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *entities.Transaction); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Transaction)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTransactionRepository_GetById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetById'
type MockTransactionRepository_GetById_Call struct {
	*mock.Call
}

// GetById is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockTransactionRepository_Expecter) GetById(ctx interface{}, id interface{}) *MockTransactionRepository_GetById_Call {
	return &MockTransactionRepository_GetById_Call{Call: _e.mock.On("GetById", ctx, id)}
}

func (_c *MockTransactionRepository_GetById_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockTransactionRepository_GetById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTransactionRepository_GetById_Call) Return(transaction *entities.Transaction, err error) *MockTransactionRepository_GetById_Call {
	_c.Call.Return(transaction, err)
	return _c
}

func (_c *MockTransactionRepository_GetById_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (*entities.Transaction, error)) *MockTransactionRepository_GetById_Call {
	_c.Call.Return(run)
	return _c
}

// GetByIdempotencyKey provides a mock function for the type MockTransactionRepository
func (_mock *MockTransactionRepository) GetByIdempotencyKey(ctx context.Context, idempotencyKey string) (*entities.Transaction, error) {
	ret := _mock.Called(ctx, idempotencyKey)

	if len(ret) == 0 {
		panic("no return value specified for GetByIdempotencyKey")
	}

	var r0 *entities.Transaction
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*entities.Transaction, error)); ok {
		return returnFunc(ctx, idempotencyKey)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *entities.Transaction); ok {
		r0 = returnFunc(ctx, idempotencyKey)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Transaction)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, idempotencyKey)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTransactionRepository_GetByIdempotencyKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByIdempotencyKey'
type MockTransactionRepository_GetByIdempotencyKey_Call struct {
	*mock.Call
}

// GetByIdempotencyKey is a helper method to define mock.On call
//   - ctx context.Context
//   - idempotencyKey string
func (_e *MockTransactionRepository_Expecter) GetByIdempotencyKey(ctx interface{}, idempotencyKey interface{}) *MockTransactionRepository_GetByIdempotencyKey_Call {
	return &MockTransactionRepository_GetByIdempotencyKey_Call{Call: _e.mock.On("GetByIdempotencyKey", ctx, idempotencyKey)}
}

func (_c *MockTransactionRepository_GetByIdempotencyKey_Call) Run(run func(ctx context.Context, idempotencyKey string)) *MockTransactionRepository_GetByIdempotencyKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTransactionRepository_GetByIdempotencyKey_Call) Return(transaction *entities.Transaction, err error) *MockTransactionRepository_GetByIdempotencyKey_Call {
	_c.Call.Return(transaction, err)
	return _c
}

func (_c *MockTransactionRepository_GetByIdempotencyKey_Call) RunAndReturn(run func(ctx context.Context, idempotencyKey string) (*entities.Transaction, error)) *MockTransactionRepository_GetByIdempotencyKey_Call {
	_c.Call.Return(run)
	return _c
}

// GetStale provides a mock function for the type MockTransactionRepository
func (_mock *MockTransactionRepository) GetStale(ctx context.Context, olderThan time.Duration, statuses []string) ([]*entities.Transaction, error) {
	ret := _mock.Called(ctx, olderThan, statuses)

	if len(ret) == 0 {
		panic("no return value specified for GetStale")
	}

	var r0 []*entities.Transaction
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Duration, []string) ([]*entities.Transaction, error)); ok {
		return returnFunc(ctx, olderThan, statuses)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Duration, []string) []*entities.Transaction); ok {
		r0 = returnFunc(ctx, olderThan, statuses)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entities.Transaction)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, time.Duration, []string) error); ok {
		r1 = returnFunc(ctx, olderThan, statuses)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTransactionRepository_GetStale_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStale'
type MockTransactionRepository_GetStale_Call struct {
	*mock.Call
}

// GetStale is a helper method to define mock.On call
//   - ctx context.Context
//   - olderThan time.Duration
//   - statuses []string
func (_e *MockTransactionRepository_Expecter) GetStale(ctx interface{}, olderThan interface{}, statuses interface{}) *MockTransactionRepository_GetStale_Call {
	return &MockTransactionRepository_GetStale_Call{Call: _e.mock.On("GetStale", ctx, olderThan, statuses)}
}

func (_c *MockTransactionRepository_GetStale_Call) Run(run func(ctx context.Context, olderThan time.Duration, statuses []string)) *MockTransactionRepository_GetStale_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 time.Duration
		if args[1] != nil {
			arg1 = args[1].(time.Duration)
		}
		var arg2 []string
		if args[2] != nil {
			arg2 = args[2].([]string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTransactionRepository_GetStale_Call) Return(transactions []*entities.Transaction, err error) *MockTransactionRepository_GetStale_Call {
	_c.Call.Return(transactions, err)
	return _c
}

func (_c *MockTransactionRepository_GetStale_Call) RunAndReturn(run func(ctx context.Context, olderThan time.Duration, statuses []string) ([]*entities.Transaction, error)) *MockTransactionRepository_GetStale_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type MockTransactionRepository
func (_mock *MockTransactionRepository) Save(ctx context.Context, transaction *entities.Transaction) error {
	ret := _mock.Called(ctx, transaction)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entities.Transaction) error); ok {
		r0 = returnFunc(ctx, transaction)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTransactionRepository_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockTransactionRepository_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - transaction *entities.Transaction
func (_e *MockTransactionRepository_Expecter) Save(ctx interface{}, transaction interface{}) *MockTransactionRepository_Save_Call {
	return &MockTransactionRepository_Save_Call{Call: _e.mock.On("Save", ctx, transaction)}
}

func (_c *MockTransactionRepository_Save_Call) Run(run func(ctx context.Context, transaction *entities.Transaction)) *MockTransactionRepository_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entities.Transaction
		if args[1] != nil {
			arg1 = args[1].(*entities.Transaction)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTransactionRepository_Save_Call) Return(err error) *MockTransactionRepository_Save_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTransactionRepository_Save_Call) RunAndReturn(run func(ctx context.Context, transaction *entities.Transaction) error) *MockTransactionRepository_Save_Call {
	_c.Call.Return(run)
	return _c
}

// EnsureIndexes provides a mock function for the type MockTransactionRepository
func (_mock *MockTransactionRepository) EnsureIndexes(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for EnsureIndexes")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTransactionRepository_EnsureIndexes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnsureIndexes'
type MockTransactionRepository_EnsureIndexes_Call struct {
	*mock.Call
}

// EnsureIndexes is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockTransactionRepository_Expecter) EnsureIndexes(ctx interface{}) *MockTransactionRepository_EnsureIndexes_Call {
	return &MockTransactionRepository_EnsureIndexes_Call{Call: _e.mock.On("EnsureIndexes", ctx)}
}

func (_c *MockTransactionRepository_EnsureIndexes_Call) Run(run func(ctx context.Context)) *MockTransactionRepository_EnsureIndexes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(arg0)
	})
	return _c
}

func (_c *MockTransactionRepository_EnsureIndexes_Call) Return(err error) *MockTransactionRepository_EnsureIndexes_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTransactionRepository_EnsureIndexes_Call) RunAndReturn(run func(ctx context.Context) error) *MockTransactionRepository_EnsureIndexes_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateStatus provides a mock function for the type MockTransactionRepository
func (_mock *MockTransactionRepository) UpdateStatus(ctx context.Context, txId uuid.UUID, status string) error {
	ret := _mock.Called(ctx, txId, status)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatus")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) error); ok {
		r0 = returnFunc(ctx, txId, status)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTransactionRepository_UpdateStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateStatus'
type MockTransactionRepository_UpdateStatus_Call struct {
	*mock.Call
}

// UpdateStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - txId uuid.UUID
//   - status string
func (_e *MockTransactionRepository_Expecter) UpdateStatus(ctx interface{}, txId interface{}, status interface{}) *MockTransactionRepository_UpdateStatus_Call {
	return &MockTransactionRepository_UpdateStatus_Call{Call: _e.mock.On("UpdateStatus", ctx, txId, status)}
}

func (_c *MockTransactionRepository_UpdateStatus_Call) Run(run func(ctx context.Context, txId uuid.UUID, status string)) *MockTransactionRepository_UpdateStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTransactionRepository_UpdateStatus_Call) Return(err error) *MockTransactionRepository_UpdateStatus_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTransactionRepository_UpdateStatus_Call) RunAndReturn(run func(ctx context.Context, txId uuid.UUID, status string) error) *MockTransactionRepository_UpdateStatus_Call {
	_c.Call.Return(run)
	return _c
}
