// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package service

import (
	"context"
	"shared/pkg/outbox"

	mock "github.com/stretchr/testify/mock"
)

// NewMockOutboxRepository creates a new instance of MockOutboxRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOutboxRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOutboxRepository {
	mock := &MockOutboxRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockOutboxRepository is an autogenerated mock type for the OutboxRepository type
type MockOutboxRepository struct {
	mock.Mock
}

type MockOutboxRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOutboxRepository) EXPECT() *MockOutboxRepository_Expecter {
	return &MockOutboxRepository_Expecter{mock: &_m.Mock}
}

// Save provides a mock function for the type MockOutboxRepository
func (_mock *MockOutboxRepository) Save(ctx context.Context, event *outbox.Event) error {
	ret := _mock.Called(ctx, event)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *outbox.Event) error); ok {
		r0 = returnFunc(ctx, event)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockOutboxRepository_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockOutboxRepository_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - event *outbox.Event
func (_e *MockOutboxRepository_Expecter) Save(ctx interface{}, event interface{}) *MockOutboxRepository_Save_Call {
	return &MockOutboxRepository_Save_Call{Call: _e.mock.On("Save", ctx, event)}
}

func (_c *MockOutboxRepository_Save_Call) Run(run func(ctx context.Context, event *outbox.Event)) *MockOutboxRepository_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *outbox.Event
		if args[1] != nil {
			arg1 = args[1].(*outbox.Event)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOutboxRepository_Save_Call) Return(err error) *MockOutboxRepository_Save_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockOutboxRepository_Save_Call) RunAndReturn(run func(ctx context.Context, event *outbox.Event) error) *MockOutboxRepository_Save_Call {
	_c.Call.Return(run)
	return _c
}
